### ISSUE TITLE
FUTURES: ETHICS AI MANIFESTO

### ISSUE THREAD

**Issue by nicoiac** [tedai-hackathon/information-2023#14]
### We will need a different COMPASS to navigate our FUTURES

In the words of Grace Hopper, **THE MOST IMPORTANT THING ABOUT TECHNOLOGY IS HOW IT CHANGES PEOPLE.** The TED AI Hackathon is more than a coding event; it's a platform to innovate responsibly. Our guiding star: technology must serve humanity. Ensure your project is anchored in ethics and drives tangible positive change.

### GUIDING PRINCIPLES
**INTENT: Purpose-Driven AI**
Every AI endeavor should carry a clear intent that addresses a societal or environmental challenge.
Code and algorithms should resonate with the project's objective, avoiding irrelevant complexities.
Project presentations should emphasize the expected positive impact of the solution.

**EQUITY: Inclusivity & Fairness**
Design solutions that celebrate diversity, tested across varied datasets to guard against bias.
Invite and value feedback from a broad spectrum of team members or mentors.
Transparently document any recognized biases or limitations.

**CLARITY: Transparency & Accountability**
Ensure comprehensive documentation: every decision, data source, and method is accessible and clear.
Be receptive to feedback, holding the project and team accountable for refining solutions.
Offer insights into the AI's decision-making process, making it interpretable and building trust among users.

**SAFEGUARD: Privacy & Data Protection**
Prioritize data ethics: use synthetic, public, or anonymized data with the necessary permissions.
Implement robust data security protocols, even in the prototype stages.
Provide comprehensive documentation on data handling and methodologies.

**ECOLOGY: Environmental Consideration & Sustainability**
Be conscious of computational resources, especially during model training, to promote energy efficiency.
Actively evaluate the environmental footprint of solutions, considering energy use and potential waste.
Aim for innovations that integrate or promote eco-friendly methodologies.

**UNITY: Open Collaboration**
Cultivate an environment where knowledge is shared, from code snippets to insights.
Embrace collaborations, even merging aligned projects for heightened impact.
Recognize and value contributions from every team member, ensuring equitable task distribution.

**CARE: Avoidance of Harm**
Be proactive in foreseeing potential misuse of AI solutions and embed preventive measures.
Continuously assess the solution during its development to rectify any harm-causing elements.
Be candid in documentation about any potential harm scenarios for full awareness.

**VISION: Future-Forward Impact**
Design solutions that envision the future, incorporating scalability and adaptability.
Reflect on the potential evolution of the challenges addressed by the AI.
Foster a spirit of continuity post-hackathon, ensuring the longevity and further enhancement of projects.

### FUTURES ESSENTIALS

**F = Focus on Impact**: Address societal or environmental challenges.
**U = Uphold Fairness & Transparency**: Guarantee bias-free solutions and clear documentation.
**T = Treasure Privacy & Nature**: Employ ethical data practices and minimize ecological impact.
**U = Unite through Collaboration**: Share insights and appreciate every contribution.
**R = Respect the EnvironmenT**: Prioritize eco-friendly methodologies and minimize waste.
**E = Envision Tomorrow**: Craft solutions with scalability and adaptability.
**S = Safeguard against Harm**: Be proactive in foreseeing potential misuses and embed preventive measures.

_______________________
**License:**
License:
This manifesto is licensed under a [Creative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/). You are free to share (copy and redistribute the material in any medium or format) for non-commercial purposes only and must provide appropriate credit.

Attribution:
When using this manifesto, please credit:

FUTURES: TED AI Manifesto by [jamming.ai](https://www.jamming.ai/).

**Comment by arun-gupta** [comment]
@palbee @nishatalagalagithub thoughts?

**Comment by palbee** [comment]
While I agree with most of their points, I'm not comfortable tacking TED onto a manifesto from a third party. 

I'd add that most of their prescriptive statements are not specific to AI, and are broadly applicable to how software impacting humans should ideally be developed.

**Comment by nishatalagalagithub** [comment]
I agree with @palbee . There are many good things about the description - but there are many good frameworks coming out about ethical and responsible AI - I dont think we need to bind to any particular one.

**Comment by palbee** [comment]
I'm inclined to close this out, particularly as I found the bolded quote attributed to Jaron Lanier. @arun-gupta what do you think?

**Comment by arun-gupta** [comment]
Agreed, lets close this and revisit later.
